#!/system/bin/sh
spath=$( cd "$(dirname "$0")" ; pwd -P )
cd $spath

source $spath/run.common

export ENV=/.bashrc #给/system/bin/sh的初始化文件， 参见(  https://android.googlesource.com/platform/system/core/+/android-4.4.4_r2.0.1/sh/main.c#185  )
chroot /data/eadb/debian/  /system/bin/sh
